// DO NOT EDIT
// Generated by: go run 9font.go -maxbpp 4 bit/anonpro/anonpro.10.font

package anonpro10

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfb01 font data, 1113 bytes, orgbpp: 8
var Xfb01 = font9.Variable{
	Info: infoXfb01, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 10, Y: 0},
		},
		LogN:   2, // 4 bpp
		Stride: 5,
		Pix:    pixXfb01, // 35 bytes
	},
}

// Xf8ff font data, 1120 bytes, orgbpp: 8
var Xf8ff = font9.Variable{
	Info: infoXf8ff, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 12, Y: 0},
		},
		LogN:   2, // 4 bpp
		Stride: 6,
		Pix:    pixXf8ff, // 42 bytes
	},
}

// Xf6c3 font data, 1080 bytes, orgbpp: 8
var Xf6c3 = font9.Variable{
	Info: infoXf6c3, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: 0},
			Max: image.Point{X: 2, Y: 2},
		},
		LogN:   2, // 4 bpp
		Stride: 1,
		Pix:    pixXf6c3, // 2 bytes
	},
}

// Xe000 font data, 1254 bytes, orgbpp: 8
var Xe000 = font9.Variable{
	Info: infoXe000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 43, Y: 1},
		},
		LogN:   2, // 4 bpp
		Stride: 22,
		Pix:    pixXe000, // 176 bytes
	},
}

// X2713 font data, 1093 bytes, orgbpp: 8
var X2713 = font9.Variable{
	Info: infoX2713, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -4},
			Max: image.Point{X: 6, Y: 1},
		},
		LogN:   2, // 4 bpp
		Stride: 3,
		Pix:    pixX2713, // 15 bytes
	},
}

// X2500 font data, 1915 bytes, orgbpp: 8
var X2500 = font9.Variable{
	Info: infoX2500, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 155, Y: 2},
		},
		LogN:   2, // 4 bpp
		Stride: 93,
		Pix:    pixX2500, // 837 bytes
	},
}

// X2324 font data, 1238 bytes, orgbpp: 8
var X2324 = font9.Variable{
	Info: infoX2324, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 39, Y: 1},
		},
		LogN:   2, // 4 bpp
		Stride: 20,
		Pix:    pixX2324, // 160 bytes
	},
}

// X221a font data, 1285 bytes, orgbpp: 8
var X221a = font9.Variable{
	Info: infoX221a, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 41, Y: 2},
		},
		LogN:   2, // 4 bpp
		Stride: 23,
		Pix:    pixX221a, // 207 bytes
	},
}

// X2116 font data, 1232 bytes, orgbpp: 8
var X2116 = font9.Variable{
	Info: infoX2116, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 43, Y: 0},
		},
		LogN:   2, // 4 bpp
		Stride: 22,
		Pix:    pixX2116, // 154 bytes
	},
}

// X2013 font data, 1411 bytes, orgbpp: 8
var X2013 = font9.Variable{
	Info: infoX2013, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 72, Y: 2},
		},
		LogN:   2, // 4 bpp
		Stride: 37,
		Pix:    pixX2013, // 333 bytes
	},
}

// X1e02 font data, 1600 bytes, orgbpp: 8
var X1e02 = font9.Variable{
	Info: infoX1e02, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 108, Y: 2},
		},
		LogN:   2, // 4 bpp
		Stride: 58,
		Pix:    pixX1e02, // 522 bytes
	},
}

// X0490 font data, 1113 bytes, orgbpp: 8
var X0490 = font9.Variable{
	Info: infoX0490, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 10, Y: 0},
		},
		LogN:   2, // 4 bpp
		Stride: 5,
		Pix:    pixX0490, // 35 bytes
	},
}

// X0384 font data, 5038 bytes, orgbpp: 8
var X0384 = font9.Variable{
	Info: infoX0384, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 773, Y: 3},
		},
		LogN:   2, // 4 bpp
		Stride: 396,
		Pix:    pixX0384, // 3960 bytes
	},
}

// X0218 font data, 1294 bytes, orgbpp: 8
var X0218 = font9.Variable{
	Info: infoX0218, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 41, Y: 2},
		},
		LogN:   2, // 4 bpp
		Stride: 24,
		Pix:    pixX0218, // 216 bytes
	},
}

// X0101 font data, 3895 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 613, Y: 2},
		},
		LogN:   2, // 4 bpp
		Stride: 313,
		Pix:    pixX0101, // 2817 bytes
	},
}

// X0000 font data, 4957 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 833, Y: 2},
		},
		LogN:   2, // 4 bpp
		Stride: 431,
		Pix:    pixX0000, // 3879 bytes
	},
}
