name: CI

env:
  go-version: stable
  ares-version: v144
  embeddedgo-version: go1.24.4-embedded

on:
  push:
    branches: [ "master", "wip" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
          cache: true

      - name: Get gotip version
        if: ${{ env.embeddedgo-version == 'gotip-embedded' }}
        id: gotip-version
        run: |
          sha=$(git ls-remote -q https://github.com/clktmr/go.git/ master-embedded | cut -f1)
          echo "SHA=$sha" >> "$GITHUB_OUTPUT"

      - name: Cache embeddedgo build
        id: embeddedgo-build
        uses: actions/cache@v4
        with:
          path: ~/sdk
          key: ${{ env.embeddedgo-version }}-${{ steps.gotip-version.outputs.SHA }}

      - name: Install Embedded Go
        run: |
          go install -v github.com/embeddedgo/dl/${{ env.embeddedgo-version }}@latest
          ${{ env.embeddedgo-version }} version || ${{ env.embeddedgo-version }} download

      - name: Install n64go tool
        run: |
          go install ./tools/n64go

      - name: Build testing binaries
        run: |
          go test -c -tags n64,debug ./rcp/... ./drivers/...
        env:
          GOENV: go.env

      - name: Upload testing binaries
        uses: actions/upload-artifact@v4
        with:
          name: testing-ROM-${{ github.sha }}
          path: ./*.elf

  run:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout ares
        uses: actions/checkout@v4
        with:
          repository: ares-emulator/ares
          path: ares
          ref: ${{ env.ares-version }}

      - name: Cache ares build
        id: ares-build
        uses: actions/cache@v4
        with:
          path: ares
          key: ares-${{ env.ares-version }}

      - name: Build ares
        working-directory: ares
        run: |
          sudo apt update -y
          sudo apt install -y cmake g++ libgtk-3-dev xvfb mesa-vulkan-drivers
          cmake -B build \
                  -DARES_CORES=n64 \
                  -DARES_ENABLE_LIBRASHADER=OFF \
                  -DARES_ENABLE_OPENAL=OFF \
                  -DARES_ENABLE_SDL=OFF \
                  -DARES_ENABLE_OSS=OFF \
                  -DARES_ENABLE_ALSA=OFF \
                  -DARES_ENABLE_PULSEAUDIO=OFF \
                  -DARES_ENABLE_AO=OFF \
                  -DARES_ENABLE_UDEV=OFF
          cd build
          make -j4
          sudo make install

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
          cache: true

      - name: Cache embeddedgo build
        id: embeddedgo-build
        uses: actions/cache@v4
        with:
          path: ~/sdk
          key: ${{ env.embeddedgo-version }}-${{ steps.gotip-version.outputs.SHA }}

      - name: Install Embedded Go
        run: |
          go install -v github.com/embeddedgo/dl/${{ env.embeddedgo-version }}@latest
          ${{ env.embeddedgo-version }} version || ${{ env.embeddedgo-version }} download

      - name: Install n64go tool
        run: go install ./tools/n64go

      - name: Run testing ROM
        run: |
          export PATH="$GITHUB_WORKSPACE/.github/workflows/:$PATH"
          go test -p 1 -tags n64,debug ./drivers/... ./rcp/...
        env:
          GOENV: go.env
          GOFLAGS: >
            '-exec=n64go rom -run=ares_headless.sh' '-toolexec=n64go toolexec' '-tags=n64' '-trimpath'
