name: CI

env:
  go-version: stable
  ares-version: v144
  embeddedgo-version: gotip-embedded

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
          cache: true

      - name: Get gotip version
        if: ${{ env.embeddedgo-version == 'gotip-embedded' }}
        id: gotip-version
        run: |
          sha=$(git ls-remote -q https://github.com/clktmr/go.git/ master-embedded | cut -f1)
          echo "SHA=$sha" >> "$GITHUB_OUTPUT"

      - name: Cache embeddedgo build
        id: embeddedgo-build
        uses: actions/cache@v4
        with:
          path: ~/sdk
          key: ${{ env.embeddedgo-version }}-${{ steps.gotip-version.outputs.SHA }}

      - name: Install Embedded Go
        run: |
          go install -v github.com/clktmr/dl/${{ env.embeddedgo-version }}@latest
          ${{ env.embeddedgo-version }} version || ${{ env.embeddedgo-version }} download
          ln -s ${{ env.embeddedgo-version }} ~/go/bin/go1.22

      - name: Install N64 tools
        run: go install ./tools/mkrom

      - name: Build testing ROM
        run: |
          go build -o test.elf ./test
          mkrom test.elf
        env:
          GOOS: noos
          GOARCH: mips64
          GOFLAGS: -tags=n64 '-ldflags=-M=0x00000000:8M -F=0x00000400:8M -stripfn=1'
          GOTOOLCHAIN: go1.22

      - name: Upload testing ROM
        uses: actions/upload-artifact@v4
        with:
          name: testing-ROM-${{ github.sha }}
          path: test.z64

  run:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout ares
        uses: actions/checkout@v4
        with:
          repository: ares-emulator/ares
          path: ares
          ref: ${{ env.ares-version }}

      - name: Cache ares build
        id: ares-build
        uses: actions/cache@v4
        with:
          path: ares
          key: ares-${{ env.ares-version }}

      - name: Build ares
        working-directory: ares
        run: |
          sudo apt install -y cmake g++ libgtk-3-dev xvfb mesa-vulkan-drivers
          cmake -B build \
                  -DARES_CORES=n64 \
                  -DARES_ENABLE_LIBRASHADER=OFF \
                  -DARES_ENABLE_OPENAL=OFF \
                  -DARES_ENABLE_SDL=OFF \
                  -DARES_ENABLE_OSS=OFF \
                  -DARES_ENABLE_ALSA=OFF \
                  -DARES_ENABLE_PULSEAUDIO=OFF \
                  -DARES_ENABLE_AO=OFF \
                  -DARES_ENABLE_UDEV=OFF
          cd build
          make -j4
          sudo make install

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
          cache: true

      - name: Install test-runner
        run: go install ./.github/workflows/test-runner

      - name: Download testing ROM
        uses: actions/download-artifact@v4
        with:
          name: testing-ROM-${{ github.sha }}

      - name: Run testing ROM
        run: |
          test-runner xvfb-run ares \
                  --setting Input/Driver=None \
                  --setting Video/Driver=None \
                  --setting Audio/Driver=None \
                  test.z64
